version: '3.6'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
